apiVersion: apps/v1
kind: Deployment
metadata:
  name: weedmasterdeployment
  namespace: jelsik
spec:
  template: # create pods using pod definition in this template
    metadata:
      labels:
        name: weed-master-deploy
    spec:
      containers:
        - name: weedmaster
          image: harbor.trask.cz/pdf_split/testrepo@sha256:ba778e02dc7194fcd11252c94a4107df9e9971f759e1133837c4100fc0c7cc97
          imagePullPolicy: Always
          args: ["-logdir","/var/containerdata/logs","master","-port","9333"]
          ports:
            - containerPort: 9333
          volumeMounts:
            - mountPath: /var/containerdata
              name: vlm
      volumes:
        - name: vlm
          hostPath:
            path: '/data/vlm'
  selector:
    matchLabels:
        name: weed-master-deploy