apiVersion: v1
kind: Service
metadata:
  name: haystackservice
  namespace: jelsik
spec:
  type: LoadBalancer
  selector:
    name: weed-master-deploy
  ports:
    - name: mport
      port: 30069
      targetPort: 9333
    - name: vport
      port: 30070
      targetPort: 8080
    - name: vgport
      port: 30071
      targetPort: 18080
