apiVersion: apps/v1
kind: Deployment
metadata:
  name: weedvolumedeployment
  namespace: jelsik
spec:
  selector:
    matchLabels:
      name: weed-master-deploy
  template:
    metadata:
      labels:
        name: weed-master-deploy
    spec:
      containers:
        - name: weedvol
          image: harbor.trask.cz/pdf_split/testrepo@sha256:ba778e02dc7194fcd11252c94a4107df9e9971f759e1133837c4100fc0c7cc97
          imagePullPolicy: Always
          args: ["-logdir","/var/containerdata/logs","volume","-port","8080"]
          ports:
            - containerPort: 8080
            - containerPort: 18080
          volumeMounts:
            - mountPath: /var/containerdata
              name: vlm
      volumes:
        - name: vlm
          hostPath:
            path: '/data/vlm'

