apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: filer
  name: filer
  namespace: jelsik
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: filer
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: filer
    spec:
      containers:
        - args:
            - filer
            - -master=master:9333
            - -metricsPort=9326
          image: chrislusf/seaweedfs
          name: filer
          ports:
            - containerPort: 8888
            - containerPort: 18888
            - containerPort: 9326
          resources: {}
          stdin: true
          tty: true
      restartPolicy: Always
status: {}
