apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: jelsik
  annotations:
    kompose.cmd: kompose --file seaweedfs-dev-compose.yml convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: filer
  name: filer
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: filer
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file seaweedfs-dev-compose.yml convert
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: filer
    spec:
      containers:
        - args:
            - filer
            - -master=master:9333
          image: chrislusf/seaweedfs:dev
          name: filer
          ports:
            - containerPort: 8888
            - containerPort: 18888
          resources: {}
      restartPolicy: Always
status: {}
