apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: jelsik
  annotations:
    kompose.cmd: kompose --file seaweedfs-dev-compose.yml convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: master
  name: master
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: master
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file seaweedfs-dev-compose.yml convert
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: master
    spec:
      containers:
        - args:
            - master
            - -ip=master
          image: chrislusf/seaweedfs:dev
          name: master
          ports:
            - containerPort: 9333
            - containerPort: 19333
          resources: {}
      restartPolicy: Always
status: {}
