---
apiVersion: v1
kind: Service
metadata:
  name: pdf-util-entry-testing
  namespace: jelsik
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 99
    targetPort: 8090
  selector:
    name: pdf-util-entry-testing