---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdf-util-entry-testing
  namespace: jelsik
spec:
  replicas: 1
  selector:
    matchLabels:
      name: pdf-util-entry-testing
  template:
    metadata:
      labels:
        name: pdf-util-entry-testing
    spec:
      containers:
        - name: application
          image: harbor.trask.cz/pdf_split/testrepo@sha256:5d0693bde8fecd7eddce91ea2e77a3bb53d8785fa649d17a0ed43f3f4a2815c2
          imagePullPolicy: Always
          ports:
            - containerPort: 8090
