---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdf-util-createthumbs-testing
  namespace: jelsik
spec:
  replicas: 1
  selector:
    matchLabels:
      name: pdf-util-createthumbs-testing
  template:
    metadata:
      labels:
        name: pdf-util-createthumbs-testing
    spec:
      containers:
        - name: application
          image: harbor.trask.cz/pdf_split/testrepo@sha256:5904ef7f15ea50d326cdb6b4bed53aad2aa9a948e9c3a9460c1a58a359028f52
          imagePullPolicy: Always
