{{- if .Values.global.enableSecurity }}
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: {{ template "seaweedfs.name" . }}-clusterissuer
  namespace: jelsik
spec:
  selfSigned: {}
{{- end }}
